### ISSUE TITLE
Failed to start nextcloud-spreed-signaling.service

### ISSUE THREAD

**Issue by dankrue80** [sunweaver/nextcloud-high-performance-backend-setup#129]
To Reproduce

1. On a fresh Debian 12 VPS
2. install the script as described here: https://github.com/sunweaver/nextcloud-high-performance-backend-setup/wiki/02-Setup-Script
3. After Installation went through successfully, enter `systemctl status`
4. See `State: degraded` with `Failed: 1 units`
5. Check which one failed with `systemctl --failed`
6. See 
![image](https://github.com/sunweaver/nextcloud-high-performance-backend-setup/assets/39704296/98f9a780-e2ee-4ffc-ad40-32dd988cf5a5)

7. Check `systemctl status nextcloud-spreed-signaling.service`
8. See 
![image](https://github.com/sunweaver/nextcloud-high-performance-backend-setup/assets/39704296/e1271ff2-1cba-4efc-a54b-087479427cbc)

Talk Settings in NC:
![image](https://github.com/sunweaver/nextcloud-high-performance-backend-setup/assets/39704296/0b0140d6-3708-4827-9a40-c5c46829b027)

**Comment by PhilDevProg** [comment]
Did you get an error message while running the script?

**Comment by dankrue80** [comment]
No, I did not recognize any error while it was running. Everything seemed to go through perfectly fine. Server is a VPS located in a datacentre in Frankfurt, so I really dont know exactly. I did not install any firewall at all, just a fresh Debian 12, nothing more.

**Comment by dankrue80** [comment]
Does the script write a log file that I can publish here. If yes, where might that be located?

**Comment by PhilDevProg** [comment]
> Does the script write a log file that I can publish here. If yes, where might that be located?

Yes, it does. It should be created in the same folder in which the script lies.

**Comment by dankrue80** [comment]
Hey there, I just did another install from scratch. First I resetted the VPS and installed Debian 12 again. Directly after, I fired the script again, which again seems to run through smooth. 

Here is the output from the script:

```
======================================================================
The Collabora Online service got installed. To set it up,
log into all of your Nextcloud instances with an adminstrator account.
	- https://cloud.mydomain.de
Then install the Nextcloud Office app and navigate to
Settings -> Administration -> Nextcloud Office.
Now select 'Use your own server' and type in 'https://nchpb.mydomain.de/collabora'.
Please note that you need to have a working HTTPS setup on your
Nextcloud server in order to get Nextcloud Office working.
======================================================================
The services coturn janus nats-server and nextcloud-signaling-spreed
got installed. To set it up, log into all of your Nextcloud
instances with an adminstrator account and install the Talk app.
Then navigate to Settings -> Administration -> Talk and put in the
settings down below.
 	- https://cloud.mydomain.de

STUN server = nchpb.mydomain.de:5349
TURN server:
 - 'turn and turns'
 - turnserver+port: nchpb.mydomain.de:5349
 - secret: 36841fea4c0571b55f000000000000000000blubbcc13f2e8d
 - 'udp & tcp'
High-performance backend:
 - https://nchpb.mydomain.de/standalone-signaling
 - cloud.mydomain.de	-> 2e0d1bb8c00000blubbe9ed25fc1c
======================================================================
SSL certificate we're installed successfully and get refreshed
automatically by Certbot.
Notifications regarding SSL-Certificates get sent to:
 - 'admin@mydomain.de'
======================================================================
Nginx got installed which acts as a reverse proxy for your selected
services.No extra configuration needed.
======================================================================
The msmtp package got successfully configured. So this system can
send emails to you now. You should have got a test email. Please
have a look and make sure you also look into your spam folder.

=== MSMTP Setup ===
E-Mails get sent to: admin@mydomain.de
E-Mail account username: m000000c
E-Mail account password: *****
E-Mail server host: w00000c.blubb.com
E-Mail server port: 587
======================================================================

Thank you for using this script. 
```

Output looks good, nothing special, right? 

Will now be looking for a log and post it here.

**Comment by dankrue80** [comment]
Unfortunately, the problem still persists. Still get Error: Server responded with: 502 back from the signaling server.

![image](https://github.com/sunweaver/nextcloud-high-performance-backend-setup/assets/39704296/7b65f34d-eeca-4b38-b725-9ee2cca697db)

Did I mention that I run my Nextcloud instance inside a docker container? Might that be relevant for the connection? But then why is the TURN server connecting like a charm.

**Comment by dankrue80** [comment]
Here is the log file (I changed sensitive data):
[setup-nextcloud-hpb-2023-11-28T18:27:11Z.log](https://github.com/sunweaver/nextcloud-high-performance-backend-setup/files/13492057/setup-nextcloud-hpb-2023-11-28T18.27.11Z.log)

Wating for your good news.

**Comment by mircokam** [comment]
We testet the script here an it works. So i close this

**Comment by dzatoah** [comment]
> Here is the log file (I changed sensitive data): [setup-nextcloud-hpb-2023-11-28T18:27:11Z.log](https://github.com/sunweaver/nextcloud-high-performance-backend-setup/files/13492057/setup-nextcloud-hpb-2023-11-28T18.27.11Z.log)
> 
> Wating for your good news.

Hey, your public v4 and v6 addresses are still visible in the log file. I thought I'll let you know.

What is the content of your `/etc/nextcloud-spreed-signaling/server.conf`

Please open a terminal and type in `journalctl -fu nextcloud-spreed-signaling`.
Then open another one and do `sudo systemctl restart nextcloud-spreed-signaling.service`

Please post the content of the first terminal.

Greetings

**Comment by dankrue80** [comment]
Hey there, thanks for reopening this issue. Will have to re-setup the VPS and re-install the script. Will inform you about the outcome when done. Regards.

**Comment by dzatoah** [comment]
Please take a look at this. This may fix your issue.
https://salsa.debian.org/go-team/packages/nextcloud-spreed-signaling/-/merge_requests/1/diffs

Please apply this patch at `/usr/lib/systemd/system/nextcloud-spreed-signaling.service`. Please test if you can make a call too :)

**Comment by dankrue80** [comment]
> > Here is the log file (I changed sensitive data): [setup-nextcloud-hpb-2023-11-28T18:27:11Z.log](https://github.com/sunweaver/nextcloud-high-performance-backend-setup/files/13492057/setup-nextcloud-hpb-2023-11-28T18.27.11Z.log)
> > Wating for your good news.
> 
> Hey, your public v4 and v6 addresses are still visible in the log file. I thought I'll let you know.
> 
> What is the content of your `/etc/nextcloud-spreed-signaling/server.conf`?
> 
> Please open a terminal and type in `journalctl -fu nextcloud-spreed-signaling`. Then open another one and do `sudo systemctl restart nextcloud-spreed-signaling.service`
> 
> Please post the content of the first terminal.
> 
> Greetings

Hey there, here is the putput of the `journalctl` terminal.
```
Jan 22 20:55:10 allsparkvps-32 systemd[1]: nextcloud-spreed-signaling.service: Scheduled restart job, restart counter is at 19.
Jan 22 20:55:10 allsparkvps-32 systemd[1]: Stopped nextcloud-spreed-signaling.service - Nextcloud Talk signaling server.
Jan 22 20:55:10 allsparkvps-32 systemd[1]: Started nextcloud-spreed-signaling.service - Nextcloud Talk signaling server.
Jan 22 20:55:10 allsparkvps-32 systemd[1]: nextcloud-spreed-signaling.service: Main process exited, code=exited, status=203/EXEC
Jan 22 20:55:10 allsparkvps-32 systemd[1]: nextcloud-spreed-signaling.service: Failed with result 'exit-code'.
Jan 22 20:55:10 allsparkvps-32 systemd[1]: nextcloud-spreed-signaling.service: Scheduled restart job, restart counter is at 20.
Jan 22 20:55:10 allsparkvps-32 systemd[1]: Stopped nextcloud-spreed-signaling.service - Nextcloud Talk signaling server.
Jan 22 20:55:10 allsparkvps-32 systemd[1]: nextcloud-spreed-signaling.service: Start request repeated too quickly.
Jan 22 20:55:10 allsparkvps-32 systemd[1]: nextcloud-spreed-signaling.service: Failed with result 'exit-code'.
Jan 22 20:55:10 allsparkvps-32 systemd[1]: Failed to start nextcloud-spreed-signaling.service - Nextcloud Talk signaling server.
Jan 22 21:03:17 allsparkvps-32 systemd[1]: Started nextcloud-spreed-signaling.service - Nextcloud Talk signaling server.
Jan 22 21:03:17 allsparkvps-32 (g-server)[22598]: nextcloud-spreed-signaling.service: Failed to locate executable /usr/local/bin/nextcloud-spreed-signaling-server: No such file or directory
Jan 22 21:03:17 allsparkvps-32 (g-server)[22598]: nextcloud-spreed-signaling.service: Failed at step EXEC spawning /usr/local/bin/nextcloud-spreed-signaling-server: No such file or directory
Jan 22 21:03:17 allsparkvps-32 systemd[1]: nextcloud-spreed-signaling.service: Main process exited, code=exited, status=203/EXEC
Jan 22 21:03:17 allsparkvps-32 systemd[1]: nextcloud-spreed-signaling.service: Failed with result 'exit-code'.
Jan 22 21:03:18 allsparkvps-32 systemd[1]: nextcloud-spreed-signaling.service: Scheduled restart job, restart counter is at 1.
Jan 22 21:03:18 allsparkvps-32 systemd[1]: Stopped nextcloud-spreed-signaling.service - Nextcloud Talk signaling server.
Jan 22 21:03:18 allsparkvps-32 systemd[1]: Started nextcloud-spreed-signaling.service - Nextcloud Talk signaling server.
Jan 22 21:03:18 allsparkvps-32 (g-server)[22600]: nextcloud-spreed-signaling.service: Failed to locate executable /usr/local/bin/nextcloud-spreed-signaling-server: No such file or directory
Jan 22 21:03:18 allsparkvps-32 (g-server)[22600]: nextcloud-spreed-signaling.service: Failed at step EXEC spawning /usr/local/bin/nextcloud-spreed-signaling-server: No such file or directory
Jan 22 21:03:18 allsparkvps-32 systemd[1]: nextcloud-spreed-signaling.service: Main process exited, code=exited, status=203/EXEC
Jan 22 21:03:18 allsparkvps-32 systemd[1]: nextcloud-spreed-signaling.service: Failed with result 'exit-code'.
Jan 22 21:03:18 allsparkvps-32 systemd[1]: nextcloud-spreed-signaling.service: Scheduled restart job, restart counter is at 2.
Jan 22 21:03:18 allsparkvps-32 systemd[1]: Stopped nextcloud-spreed-signaling.service - Nextcloud Talk signaling server.
Jan 22 21:03:18 allsparkvps-32 systemd[1]: Started nextcloud-spreed-signaling.service - Nextcloud Talk signaling server.
Jan 22 21:03:18 allsparkvps-32 (g-server)[22602]: nextcloud-spreed-signaling.service: Failed to locate executable /usr/local/bin/nextcloud-spreed-signaling-server: No such file or directory
Jan 22 21:03:18 allsparkvps-32 (g-server)[22602]: nextcloud-spreed-signaling.service: Failed at step EXEC spawning /usr/local/bin/nextcloud-spreed-signaling-server: No such file or directory
Jan 22 21:03:18 allsparkvps-32 systemd[1]: nextcloud-spreed-signaling.service: Main process exited, code=exited, status=203/EXEC
Jan 22 21:03:18 allsparkvps-32 systemd[1]: nextcloud-spreed-signaling.service: Failed with result 'exit-code'.
Jan 22 21:03:18 allsparkvps-32 systemd[1]: nextcloud-spreed-signaling.service: Scheduled restart job, restart counter is at 3.
Jan 22 21:03:18 allsparkvps-32 systemd[1]: Stopped nextcloud-spreed-signaling.service - Nextcloud Talk signaling server.
Jan 22 21:03:18 allsparkvps-32 (g-server)[22603]: nextcloud-spreed-signaling.service: Failed to locate executable /usr/local/bin/nextcloud-spreed-signaling-server: No such file or directory
Jan 22 21:03:18 allsparkvps-32 systemd[1]: Started nextcloud-spreed-signaling.service - Nextcloud Talk signaling server.
Jan 22 21:03:18 allsparkvps-32 (g-server)[22603]: nextcloud-spreed-signaling.service: Failed at step EXEC spawning /usr/local/bin/nextcloud-spreed-signaling-server: No such file or directory
Jan 22 21:03:18 allsparkvps-32 systemd[1]: nextcloud-spreed-signaling.service: Main process exited, code=exited, status=203/EXEC
Jan 22 21:03:18 allsparkvps-32 systemd[1]: nextcloud-spreed-signaling.service: Failed with result 'exit-code'.
Jan 22 21:03:18 allsparkvps-32 systemd[1]: nextcloud-spreed-signaling.service: Scheduled restart job, restart counter is at 4.
Jan 22 21:03:18 allsparkvps-32 systemd[1]: Stopped nextcloud-spreed-signaling.service - Nextcloud Talk signaling server.
Jan 22 21:03:19 allsparkvps-32 (g-server)[22604]: nextcloud-spreed-signaling.service: Failed to locate executable /usr/local/bin/nextcloud-spreed-signaling-server: No such file or directory
Jan 22 21:03:19 allsparkvps-32 systemd[1]: Started nextcloud-spreed-signaling.service - Nextcloud Talk signaling server.
Jan 22 21:03:19 allsparkvps-32 (g-server)[22604]: nextcloud-spreed-signaling.service: Failed at step EXEC spawning /usr/local/bin/nextcloud-spreed-signaling-server: No such file or directory
Jan 22 21:03:19 allsparkvps-32 systemd[1]: nextcloud-spreed-signaling.service: Main process exited, code=exited, status=203/EXEC
Jan 22 21:03:19 allsparkvps-32 systemd[1]: nextcloud-spreed-signaling.service: Failed with result 'exit-code'.
Jan 22 21:03:19 allsparkvps-32 systemd[1]: nextcloud-spreed-signaling.service: Scheduled restart job, restart counter is at 5.
Jan 22 21:03:19 allsparkvps-32 systemd[1]: Stopped nextcloud-spreed-signaling.service - Nextcloud Talk signaling server.
Jan 22 21:03:19 allsparkvps-32 systemd[1]: nextcloud-spreed-signaling.service: Start request repeated too quickly.
Jan 22 21:03:19 allsparkvps-32 systemd[1]: nextcloud-spreed-signaling.service: Failed with result 'exit-code'.
Jan 22 21:03:19 allsparkvps-32 systemd[1]: Failed to start nextcloud-spreed-signaling.service - Nextcloud Talk signaling server.
```

**Comment by dankrue80** [comment]
> Please take a look at this. This may fix your issue. https://salsa.debian.org/go-team/packages/nextcloud-spreed-signaling/-/merge_requests/1/diffs
> 
> Please apply this patch at `/usr/lib/systemd/system/nextcloud-spreed-signaling.service`. Please test if you can make a call too :)

Hey again,

unfortunately I don't really get the point of how I have to apply the patch to `/usr/lib/systemd/system/nextcloud-spreed-signaling.service`. Any help on this will be highly appreciated.

Here is the content of my `/usr/lib/systemd/system/nextcloud-spreed-signaling.service`:
```
[Unit]
Description=Nextcloud Talk signaling server

[Service]
ExecStart=/usr/local/bin/nextcloud-spreed-signaling-server --config /etc/nextcloud-spreed-signaling/server.conf
User=_signaling
Group=_signaling
Restart=on-failure

[Install]
WantedBy=multi-user.target
```

What exactly do I have to apply here? Waiting for your good news. Best regards!

**Comment by de-maebinger** [comment]
Hello,
briefly mentioned in passing... I have exactly the same error!
I did a fresh installation with Debian 12 and the script 1.2.4. Unfortunately I also get the error "Server responded with: 502"
The Spreed service does not start up.
I am curious how things will continue here! 
I would also send a few logs, but I have reinstalled too often that I am currently not receiving any new Zerts from LetsEncrypt. I may be able to send something tomorrow.

Many thanks for any information from me too!

**Comment by dzatoah** [comment]
> What exactly do I have to apply here? Waiting for your good news. Best regards!

Mh the `ExecPaths` line is missing. Which version of nextcloud-spreed-signaling do you have installed? `dpkg - l nextcloud-spreed-signaling`.

The version should be `1.2.2-1~bpo12+1`. If not, execute `apt reinstall -t bookworm-backports nextcloud-spreed-signaling` as a root user.

And then finally apply the patch as I suggested.


This issue(s) is/are known and is/are already fixed. A new script version will be released soon, I guess.

**Comment by dankrue80** [comment]
> Which version of nextcloud-spreed-signaling do you have installed? `dpkg -l nextcloud-spreed-signaling`.

Mhh, I get the following output: `dpkg-query: no packages found matching nextcloud-spreed-signaling`

What am I missing here?

**Comment by dankrue80** [comment]
> The version should currently be `1.2.2-1~bpo12+1`. If not, execute `apt reinstall -t bookworm-backports nextcloud-spreed-signaling` as a root user.

This unfortunately doesn't work either. I am not a Debian pro, so I don't really understand what this output means:
`E: The value 'bookworm-backports' is invalid for APT::Default-Release as such a release is not available in the sources`

**Comment by dankrue80** [comment]
> Mh the `ExecPaths` line is missing

I added the `ExecPaths` line like this:
```
[Unit]
Description=Nextcloud Talk signaling server

[Service]
ExecStart=/usr/local/bin/nextcloud-spreed-signaling-server --config /etc/nextcloud-spreed-signaling/server.conf
ExecPaths=/usr/bin/nextcloud-spreed-signaling-server /usr/lib
User=_signaling
Group=_signaling
Restart=on-failure

[Install]
WantedBy=multi-user.target
```

I restarted the service but it still fails when checking the status with`systemctl status nextcloud-spreed-signaling.service`.

**Comment by dankrue80** [comment]
Do you suggest to re-install a fresh Debian 12 first?

**Comment by dzatoah** [comment]
> Do you suggest to re-install a fresh Debian 12 first?

Yeah, it probably should be a fresh installation. Although I've tested it with a broken install too.

**Comment by dankrue80** [comment]
The script doesn't go through. It always stops when executing Certbot and requesting a certificate. Maybe it is just something with my subdomain and a possible ratelimit? Don't know, but this is the output:

```
An unexpected error occurred:
AttributeError: can't set attribute
Ask for help or search for solutions at https://community.letsencrypt.org. See the logfile /var/log/letsencrypt/letsencrypt.log or re-run Certbot with -v for more details.
Something wen't wrong while starting Certbot.
Maybe the error is in the nextcloud-hpb.conf file (please read the error message above).
```

**Comment by de-maebinger** [comment]
This sounds like you have reached the limit of LetsEncrypt, like me :)
here /var/log/letsencrypt/letsencrypt.log you read whats the problem in detail

**Comment by mh-74** [comment]
Hello, I have the same error on my VPS. During the installation I noticed that Go version 1.20 is needed for a short time. The script continues to run, but in the end the signaling server does not work. When I check my Go version, it says go1.19.8 linux/amd64. Is there possibly a connection here?  In the folder /etc/nextcloud-spreed-signaling there is also only the file server.conf.

**Comment by jandechent** [comment]
Dear all, somehow I ended up here too. I followed the steps in post above on a fresh install (git checkout pr/fixup-support-debian-13)

STarting the service does not work, but manually starting does. Any tipps?

```
root@localhost:~# /usr/bin/nextcloud-spreed-signaling-server --config /etc/nextcloud-spreed-signaling/server.conf 
2024-01-23 15:46:49.901635 I | main.go:133: Starting up version unreleased/go1.19.8 as pid 1545
2024-01-23 15:46:49.903435 I | main.go:142: Using a maximum of 2 CPUs
2024-01-23 15:46:49.914955 I | natsclient.go:108: Connection established to nats://localhost:4222 (NAU33VEJB5WHYHHHGA7ZHDI4MLUO63P53JEG2VDJYNQHYLP7ZRXAWJVQ)
2024-01-23 15:46:49.924776 I | grpc_common.go:167: WARNING: No GRPC server certificate and/or key configured, running unencrypted
2024-01-23 15:46:49.925374 I | grpc_common.go:169: WARNING: No GRPC CA configured, expecting unencrypted connections
2024-01-23 15:46:49.925741 I | hub.go:190: WARNING: No shared secret has been set for internal clients.
2024-01-23 15:46:49.926221 I | backend_storage_static.go:72: Backend nextcloud-backend-0 added for https://cloud.jandechent.de/
2024-01-23 15:46:49.926516 I | backend_storage_static.go:72: Backend nextcloud-backend-1 added for https://cloud.lott-festival.de/
2024-01-23 15:46:49.926697 I | hub.go:202: Using a maximum of 8 concurrent backend connections per host
2024-01-23 15:46:49.926865 I | hub.go:209: Using a timeout of 10s for backend connections
2024-01-23 15:46:49.927078 I | hub.go:262: Not using GeoIP database
2024-01-23 15:46:49.936073 I | mcu_janus.go:292: Connected to Janus WebRTC Server 1.1.2 by Meetecho s.r.l.
2024-01-23 15:46:49.936235 I | mcu_janus.go:298: Found JANUS VideoRoom plugin 0.0.9 by Meetecho s.r.l.
2024-01-23 15:46:49.936341 I | mcu_janus.go:303: Data channels are supported
2024-01-23 15:46:49.936441 I | mcu_janus.go:307: Full-Trickle is enabled
2024-01-23 15:46:49.936541 I | mcu_janus.go:309: Maximum bandwidth 1048576 bits/sec per publishing stream
2024-01-23 15:46:49.936643 I | mcu_janus.go:310: Maximum bandwidth 2097152 bits/sec per screensharing stream
2024-01-23 15:46:49.938067 I | mcu_janus.go:316: Created Janus session 7226984903916989
2024-01-23 15:46:49.938716 I | mcu_janus.go:323: Created Janus handle 8305304231358577
2024-01-23 15:46:49.938847 I | main.go:263: Using janus MCU
2024-01-23 15:46:49.938952 I | hub.go:387: Using a timeout of 10s for MCU requests
2024-01-23 15:46:49.939068 I | backend_server.go:98: Using configured TURN API key
2024-01-23 15:46:49.939172 I | backend_server.go:99: Using configured shared TURN secret
2024-01-23 15:46:49.939273 I | backend_server.go:101: Adding "turn:123df1c.online-server.cloud:9991?transport=udp" as TURN server
2024-01-23 15:46:49.939412 I | backend_server.go:101: Adding "turn:123df1c.online-server.cloud:9991?transport=tcp" as TURN server
2024-01-23 15:46:49.939553 I | backend_server.go:114: No IPs configured for the stats endpoint, only allowing access from 127.0.0.1
2024-01-23 15:46:49.941348 I | main.go:339: Listening on 127.0.0.1:8080
```


```
root@localhost:~# systemctl status nextcloud-spreed-signaling
× nextcloud-spreed-signaling.service - Nextcloud Talk signaling server
     Loaded: loaded (/lib/systemd/system/nextcloud-spreed-signaling.service; enabled; preset: enabled)
     Active: failed (Result: exit-code) since Tue 2024-01-23 15:41:39 UTC; 3min 27s ago
   Duration: 21ms
    Process: 1533 ExecStart=/usr/bin/nextcloud-spreed-signaling-server --config /etc/nextcloud-spreed-signaling/server.conf (code=exited, status=226/NAMESPACE)
   Main PID: 1533 (code=exited, status=226/NAMESPACE)
        CPU: 19ms

Jan 23 15:41:39 localhost systemd[1]: nextcloud-spreed-signaling.service: Scheduled restart job, restart counter is at 5.
Jan 23 15:41:39 localhost systemd[1]: Stopped nextcloud-spreed-signaling.service - Nextcloud Talk signaling server.
Jan 23 15:41:39 localhost systemd[1]: nextcloud-spreed-signaling.service: Start request repeated too quickly.
Jan 23 15:41:39 localhost systemd[1]: nextcloud-spreed-signaling.service: Failed with result 'exit-code'.
Jan 23 15:41:39 localhost systemd[1]: Failed to start nextcloud-spreed-signaling.service - Nextcloud Talk signaling server.
root@localhost:~# 
```


```
Jan 23 15:19:48 localhost systemd[1]: Started nextcloud-spreed-signaling.service - Nextcloud Talk signaling server.
Jan 23 15:19:48 localhost (g-server)[7550]: nextcloud-spreed-signaling.service: Failed to set up mount namespacing: /run/systemd/unit-root/usr/bin/signaling: No such file or directory
Jan 23 15:19:48 localhost (g-server)[7550]: nextcloud-spreed-signaling.service: Failed at step NAMESPACE spawning /usr/bin/nextcloud-spreed-signaling-server: No such file or directory
Jan 23 15:19:48 localhost systemd[1]: nextcloud-spreed-signaling.service: Main process exited, code=exited, status=226/NAMESPACE
Jan 23 15:19:48 localhost systemd[1]: nextcloud-spreed-signaling.service: Failed with result 'exit-code'.
Jan 23 15:19:49 localhost systemd[1]: nextcloud-spreed-signaling.service: Scheduled restart job, restart counter is at 1.
Jan 23 15:19:49 localhost systemd[1]: Stopped nextcloud-spreed-signaling.service - Nextcloud Talk signaling server.
Jan 23 15:19:49 localhost systemd[1]: Started nextcloud-spreed-signaling.service - Nextcloud Talk signaling server.
Jan 23 15:19:49 localhost (g-server)[7558]: nextcloud-spreed-signaling.service: Failed to set up mount namespacing: /run/systemd/unit-root/usr/bin/signaling: No such file or directory
Jan 23 15:19:49 localhost (g-server)[7558]: nextcloud-spreed-signaling.service: Failed at step NAMESPACE spawning /usr/bin/nextcloud-spreed-signaling-server: No such file or directory
Jan 23 15:19:49 localhost systemd[1]: nextcloud-spreed-signaling.service: Main process exited, code=exited, status=226/NAMESPACE
Jan 23 15:19:49 localhost systemd[1]: nextcloud-spreed-signaling.service: Failed with result 'exit-code'.
Jan 23 15:19:51 localhost systemd[1]: nextcloud-spreed-signaling.service: Scheduled restart job, restart counter is at 2.
```

**Comment by dzatoah** [comment]
Please take a look at this. This may fix your issue.
https://salsa.debian.org/go-team/packages/nextcloud-spreed-signaling/-/merge_requests/1/diffs

Please apply this patch at /usr/lib/systemd/system/nextcloud-spreed-signaling.service. Please test if you can make a call too :)

@jandechent

**Comment by sunweaver** [comment]
This issue should resolve once nextcloud-spreed-signaling 1.2.2-3~bpo12+1 has landed in Debian bookworm-backports. This should be in +/- 4 days from now. I uploaded the fixed testing/unstable version today, the backports version has been uploaded with a delay of four days. Please retest with sane and tested signaling server package once the version referenced above is available.

You also need to run this script from Git's main branch. Release will come soon, too. (Some more tasks to accomplish before the release).

**Comment by jandechent** [comment]
Loos very good. Service starts and the test works (using allow all and this client binary on the server. 
`All connections established`

However, calling fails: No MCU publisher found for session, which seems to be a debian thing
[https://groups.google.com/g/linux.debian.bugs.dist/c/KG50JMP_UYY](url)

I think I will try the "compile from sources way"

**Comment by de-maebinger** [comment]
Hi,
I have now simply reinstalled everything, but before running the script I installed "go" in the current version.
I pulled the certificates in staging mode. (I'm still out of action until Friday).
The "nextcloud spreed" service also came up cleanly for me.
If I now deactivate the certificate check in the HPB of Talk, I get a green tick.

It seems to be due to "Go". I won't be able to say for sure until Friday.
Thanks for the help
